### ISSUE TITLE
为什么老是报错，我图片格式没问题啊

### ISSUE THREAD

**Issue by yarnra** [XiaoMiku01/custom_bilibili_nft#6]
C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\python.exe "C:/Users/Lenovo/Desktop/新建文件夹 (2)/e3a04a534df2957d0f1e72a9ea76202a-1612350c00088ab59cd523828090cc41c169073d/nft.py"
  File "C:\Users\Lenovo\Desktop\新建文件夹 (2)\e3a04a534df2957d0f1e72a9ea76202a-1612350c00088ab59cd523828090cc41c169073d\nft.py", line 12
    FACE_PATH = "C:\Users\Lenovo\Desktop\face.jpg"  # 头像路径 推荐正方形
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

进程已结束,退出代码1

**Comment by XiaoMiku01** [comment]
改成 FACE_PATH = r"C:\Use...
